Summary: Mac OS X native dependencies.
Name: macosx-base
Version: 10.4
Release: 0.%(date +"%%Y%m%d")
License: none
Group: MacPorts

Provides: org.macports.darwin8

# XXX /System/Library/Frameworks
Provides: AGL
Provides: Accelerate
Provides: AGL
Provides: Accelerate
Provides: AddressBook
Provides: AppKit
Provides: AppKitScripting
Provides: AppleScriptKit
Provides: AppleShareClient
Provides: AppleShareClientCore
Provides: AppleTalk
Provides: ApplicationServices
Provides: AudioToolbox
Provides: AudioUnit
Provides: Automator
Provides: CPlusTest
Provides: Carbon
Provides: Cocoa
Provides: CoreAudio
Provides: CoreAudioKit
Provides: CoreData
Provides: CoreFoundation
Provides: CoreMIDI
Provides: CoreMIDIServer
Provides: CoreServices
Provides: DVComponentGlue
Provides: DVDPlayback
Provides: DirectoryService
Provides: DiscRecording
Provides: DiscRecordingUI
Provides: DiskArbitration
Provides: DrawSprocket
Provides: EOModeler
Provides: ExceptionHandling
Provides: FWAUserLib
Provides: ForceFeedback
Provides: Foundation
Provides: GLUT
Provides: ICADevices
Provides: IOBluetooth
Provides: IOBluetoothUI
Provides: IOKit
Provides: InstallerPlugins
Provides: InstantMessage
Provides: InterfaceBuilder
Provides: JDBCEOAdaptor
Provides: JNDIEOAdaptor
Provides: JavaDTWGeneration
Provides: JavaDirectToWeb
Provides: JavaEOAccess
Provides: JavaEOApplication
Provides: JavaEOCocoa
Provides: JavaEOControl
Provides: JavaEODistribution
Provides: JavaEOGeneration
Provides: JavaEOInterface
Provides: JavaEOInterfaceCocoa
Provides: JavaEOInterfaceSwing
Provides: JavaEOProject
Provides: JavaEORuleSystem
Provides: JavaEOTool
Provides: JavaEmbedding
Provides: JavaFoundation
Provides: JavaJDBCAdaptor
Provides: JavaJNDIAdaptor
Provides: JavaVM
Provides: JavaWOExtensions
Provides: JavaWOJSPServlet
Provides: JavaWebObjects
Provides: JavaWebServicesClient
Provides: JavaWebServicesGeneration
Provides: JavaWebServicesSupport
Provides: JavaXML
Provides: Kerberos
Provides: Kernel
Provides: LDAP
Provides: Message
Provides: OSAKit
Provides: OpenAL
Provides: OpenGL
Provides: PCSC
Provides: PreferencePanes
Provides: Python
Provides: QTKit
Provides: Quartz
Provides: QuartzCore
Provides: QuickTime
Provides: ScreenSaver
Provides: Scripting
Provides: Security
Provides: SecurityFoundation
Provides: SecurityInterface
Provides: SenTestingKit
Provides: SyncServices
Provides: System
Provides: SystemConfiguration
Provides: TWAIN
Provides: Tcl
Provides: Tk
Provides: WebKit
Provides: XgridFoundation
Provides: vecLib

# XXX X11 libraries
Provides: libAppleWM.1.dylib
Provides: libFS.6.dylib
Provides: libGL.1.dylib
Provides: libGLU.1.dylib
Provides: libICE.6.dylib
Provides: libMrm.4.dylib
Provides: libOSMesa.4.dylib
Provides: libSM.6.dylib
Provides: libUil.4.dylib
Provides: libX11.6.dylib
Provides: libXRes.1.dylib
Provides: libXTrap.6.dylib
Provides: libXaw.6.dylib
Provides: libXaw.7.dylib
Provides: libXcursor.1.dylib
Provides: libXext.6.dylib
Provides: libXfont.1.dylib
Provides: libXfontcache.1.dylib
Provides: libXft.1.dylib
Provides: libXft.2.dylib
Provides: libXi.6.dylib
Provides: libXinerama.1.dylib
Provides: libXm.4.dylib
Provides: libXmu.6.dylib
Provides: libXmuu.1.dylib
Provides: libXp.6.dylib
Provides: libXpm.4.dylib
Provides: libXrandr.2.dylib
Provides: libXrender.1.dylib
Provides: libXss.1.dylib
Provides: libXt.6.dylib
Provides: libXtst.6.dylib
Provides: libXv.1.dylib
Provides: libXvMC.1.dylib
Provides: libXxf86misc.1.dylib
Provides: libXxf86vm.1.dylib
Provides: libdps.1.dylib
Provides: libdpstk.1.dylib
Provides: libexpat.0.dylib
Provides: libfontconfig.1.dylib
Provides: libfontenc.1.dylib
Provides: libfreetype.6.dylib
Provides: liboldX.6.dylib
Provides: libpsres.1.dylib
Provides: libxkbfile.1.dylib
Provides: libxkbui.1.dylib

Provides: apop.so
Provides: architecture
Provides: bigdecimal.bundle
Provides: cap.so
Provides: clone.so
Provides: compctl.so
Provides: complete.so
Provides: complist.so
Provides: computil.so
Provides: cparse.bundle
Provides: darwin_acls.so
Provides: datetime.so
Provides: dbm.bundle
Provides: deltochar.so
Provides: dhx.so
Provides: digest.bundle
Provides: digestmd5WebDAV.so
Provides: dl.bundle
Provides: enumerator.bundle
Provides: etc.bundle
Provides: example.so
Provides: fcntl.bundle
Provides: files.so
Provides: langinfo.so
Provides: libAppKitJava.B.dylib
Provides: libBSDPClient.A.dylib
Provides: libDHCPServer.A.dylib
Provides: libEOAccessJava.A.dylib
Provides: libEOControlJava.A.dylib
Provides: libFoundationJava.B.dylib
Provides: libMallocDebug.A.dylib
Provides: libObjCJava.A.dylib
Provides: libPrintServiceQuota.1.dylib
Provides: libPureAppKitJava.B.dylib
Provides: libSystem.B.dylib
Provides: libSystem.B_debug.dylib
Provides: libSystem.B_profile.dylib
Provides: libXplugin.1.dylib
Provides: libalias.A.dylib
Provides: libanonymous.2.so
Provides: libauto.dylib
Provides: libbsm.dylib
Provides: libbz2.1.0.dylib
Provides: libcharset.1.dylib
Provides: libcrammd5.2.so
Provides: libcrypto.0.9.7.dylib
Provides: libcrypto.0.9.dylib
Provides: libcups.2.dylib
Provides: libcupsimage.2.dylib
Provides: libcurl.3.dylib
Provides: libdigestmd5.2.so
Provides: libedit.2.dylib
Provides: libexpressionextensionsjava.A.dylib
Provides: libexslt.0.dylib
Provides: libform.5.4.dylib
Provides: libform.5.dylib
Provides: libgcc_s.1.dylib
Provides: libgcc_s_ppc64.1.0.dylib
Provides: libgimpprint.7.dylib
Provides: libgmalloc.B.dylib
Provides: libgssapiv2.2.0.18.so
Provides: libiconv.2.dylib
Provides: libicucore.A.dylib
Provides: libiodbc.2.dylib
Provides: libiodbcinst.2.dylib
Provides: libipsec.A.dylib
Provides: libkerberos4.2.so
Provides: libltdl.3.dylib
Provides: libmathCommon.A.dylib
Provides: libmathCommon.A_debug.dylib
Provides: libmathCommon.A_profile.dylib
Provides: libmenu.5.4.dylib
Provides: libmenu.5.dylib
Provides: libmx.A.dylib
Provides: libmx.A_debug.dylib
Provides: libmx.A_profile.dylib
Provides: libncurses.5.4.dylib
Provides: libncurses.5.dylib
Provides: libnetsnmp.5.dylib
Provides: libnetsnmpagent.5.dylib
Provides: libnetsnmphelpers.5.dylib
Provides: libnetsnmpmibs.5.dylib
Provides: libntlm.so
Provides: libobjc.A.dylib
Provides: libobjc_profile.A.dylib
Provides: libotp.2.so
Provides: libpam.1.dylib
Provides: libpanel.5.4.dylib
Provides: libpanel.5.dylib
Provides: libpcap.A.dylib
Provides: libplain.2.so
Provides: libpscrammd5.2.so
Provides: libresolv.9.dylib
Provides: libruby.1.dylib
Provides: libsasl2.2.dylib
Provides: libsasldb.2.so
Provides: libsql.so
Provides: libsqlite3.0.dylib
Provides: libssl.0.9.7.dylib
Provides: libssl.0.9.dylib
Provides: libstdc++.6.dylib
Provides: libtcl8.3.dylib
Provides: libtclsqlite3.0.dylib
Provides: libtidy.A.dylib
Provides: libwrap.7.dylib
Provides: libwx_macud-2.5.3.dylib
Provides: libwx_macud_gizmos-2.5.3.dylib
Provides: libwx_macud_gl-2.5.3.dylib
Provides: libwx_macud_ogl-2.5.3.dylib
Provides: libwx_macud_stc-2.5.3.dylib
Provides: libxml2.2.dylib
Provides: libxslt.1.dylib
Provides: libz.1.dylib
Provides: login.so
Provides: mapfile.so
Provides: mathfunc.so
Provides: md5.bundle
Provides: mschapv2.so
Provides: nkf.bundle
Provides: opendirectory.so
Provides: opendirectorysam.so
Provides: openssl.bundle
Provides: pam_afpmount.so
Provides: pam_deny.so
Provides: pam_netinfo.so
Provides: pam_nologin.so
Provides: pam_permit.so
Provides: pam_rootok.so
Provides: pam_securetty.so
Provides: pam_securityserver.so
Provides: pam_unix.so
Provides: pam_uwtmp.so
Provides: pam_wheel.so
Provides: parameter.so
Provides: pty.bundle
Provides: rlimits.so
Provides: rmd160.bundle
Provides: sched.so
Provides: sdbm.bundle
Provides: sha1.bundle
Provides: sha2.bundle
Provides: shadow_auxprop.so
Provides: smb_lm.so
Provides: smb_nt.so
Provides: smb_ntlmv2.so
Provides: socket.bundle
Provides: socket.so
Provides: stat.so
Provides: stringio.bundle
Provides: strscan.bundle
Provides: syck.bundle
Provides: syslog.bundle
Provides: system.so
Provides: tcltklib.bundle
Provides: tcp.so
Provides: termcap.so
Provides: terminfo.so
Provides: tkutil.bundle
Provides: twowayrandom.so
Provides: wait.bundle
Provides: zftp.so
Provides: zle.so
Provides: zleparameter.so
Provides: zlib.bundle
Provides: zprof.so
Provides: zpty.so
Provides: zselect.so
Provides: zutil.so
Provides: /bin/sh
Provides: /bin/csh
Provides: /bin/ksh
Provides: /usr/bin/wish
Provides: /usr/bin/tclsh
Provides: /usr/bin/perl
Provides: /usr/bin/awk


%description
This is a virtual RPM package.  It contains no actual files.  It uses the
`Provides' token from RPM 3.x and later to list many of the shared libraries
and interpreters that are part of the base operating system and associated
OS packages for Darwin.

%prep
# nothing to do
%build
# nothing to do
%install
# nothing to do
%clean
# nothing to do

%files
# no files in a virtual package
